### ISSUE TITLE
SDL2 interop

### ISSUE THREAD

**Issue by rosshadden** [Halsys/nim-bgfx#3]
Can the [SDL2 library](https://github.com/nim-lang/sdl2) be used with this?

**Comment by auRose94** [comment]
No, but you can use [this](https://github.com/Vladar4/sdl2_nim/blob/master/sdl2/sdl_syswm.nim#L293) library. The library has the function and structures you need. You specifically need a wrapper to SDL_GetWindowWMInfo and a complete structure definition of SDL_SysWMinfo. Then you need to rewrite [this](https://github.com/Halsys/nim-bgfx/blob/master/examples/platform.nim#L26) function to work with SDL2 instead of GLFW. Get the platform dependent handle of the window and give it to BGFX's platform data. Then you will need to rewrite the events system so you have window resizing.

**Comment by rawsp33d** [comment]
This is a great answer.  If you don't mind, can you explain why we can't use the lib I linked to?  That is, what would need to happen for it to be used?

Realistically I have used neither SDL lib yet and thus have no opinions on them; I am merely curious.

**Comment by auRose94** [comment]
Sorry for not replying sooner. I had work and exhausted myself. Anyway, a while back I attempted to use that library you linked. I mentioned using another lib because it is more complete and doesn't have you do tedious work in figuring out the layout.

See [here](https://github.com/nim-lang/sdl2/blob/master/src/sdl2.nim#L308)...
You would need to cast "padding" to the correct type. If for instance the "subsystem" is "SysWM_Windows", then you would cast "padding" to the windows structure from "[SDL_syswm.h](https://github.com/spurious/SDL-mirror/blob/master/include/SDL_syswm.h#L202)". Then you could get the window handle and pass it to bgfx. 

nim-bgfx's examples can be rewritten with nim-lang/SDL2. I could send a pull request adding the correct structures to nim-lang/SDL2. Right now I have an issue I think is related to [nimrod-glfw](https://github.com/Halsys/nimrod-glfw) and could stand to rewrite the examples with nim-lang/SDL2 instead. I don't really have time to work on redoing those examples though. I will try to add another example when I do eventually work on it.

I'm going to close this but I will get around to making those examples.
